#Artificial Neural Network

##Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
tf.__version__

'2.14.0'

## Data Preprocessing

### Importing dataset

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/data/Churn_Modelling.csv")

In [ ]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
X = df.drop(["RowNumber","CustomerId","Surname","Exited"],axis=1)

In [ ]:
y = df["Exited"]

In [ ]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [ ]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

### Encoding categorical data

#### Label encoding the Gender column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X["Gender"] = le.fit_transform(X["Gender"])

In [ ]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,0,42,2,0.00,1,1,1,101348.88
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58
2,502,France,0,42,8,159660.80,3,1,0,113931.57
3,699,France,0,39,1,0.00,2,0,0,93826.63
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64
9996,516,France,1,35,10,57369.61,1,1,1,101699.77
9997,709,France,0,36,7,0.00,1,0,1,42085.58
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52
9999,792,France,0,28,4,130142.79,1,1,0,38190.78

In [ ]:
X["Geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
X[["France","Germany","Spain"]]= pd.get_dummies(X["Geography"])

In [ ]:
X = X.drop("Geography",axis=1)

### Splitting the dataset into training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN

###Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

## Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

### Training the ANN on the training set

In [ ]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
210/210 [==============================] - 2s 3ms/step - loss: 0.6702 - accuracy: 0.6352
Epoch 2/100
210/210 [==============================] - 0s 2ms/step - loss: 0.5090 - accuracy: 0.7919
Epoch 3/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4637 - accuracy: 0.7921
Epoch 4/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4458 - accuracy: 0.7975
Epoch 5/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4361 - accuracy: 0.8036
Epoch 6/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4307 - accuracy: 0.8064
Epoch 7/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4259 - accuracy: 0.8087
Epoch 8/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4211 - accuracy: 0.8133
Epoch 9/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4154 - accuracy: 0.8184
Epoch 10/100
210/210 [==============================] - 1s 2ms/step - loss: 0.4082 - accuracy: 0.8237
Epoch 11/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3992 - accuracy: 0.8310
Epoch 12/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3905 - accuracy: 0.8369
Epoch 13/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3812 - accuracy: 0.8416
Epoch 14/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3738 - accuracy: 0.8443
Epoch 15/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3674 - accuracy: 0.8482
Epoch 16/100
210/210 [==============================] - 1s 2ms/step - loss: 0.3622 - accuracy: 0.8485
Epoch 17/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3589 - accuracy: 0.8512
Epoch 18/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3560 - accuracy: 0.8528
Epoch 19/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3555 - accuracy: 0.8530
Epoch 20/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3533 - accuracy: 0.8537
Epoch 21/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3528 - accuracy: 0.8533
Epoch 22/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3522 - accuracy: 0.8530
Epoch 23/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3513 - accuracy: 0.8539
Epoch 24/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3507 - accuracy: 0.8533
Epoch 25/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3503 - accuracy: 0.8546
Epoch 26/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3492 - accuracy: 0.8540
Epoch 27/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3488 - accuracy: 0.8561
Epoch 28/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3484 - accuracy: 0.8540
Epoch 29/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3481 - accuracy: 0.8540
Epoch 30/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3475 - accuracy: 0.8545
Epoch 31/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3471 - accuracy: 0.8546
Epoch 32/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3465 - accuracy: 0.8545
Epoch 33/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3460 - accuracy: 0.8554
Epoch 34/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3459 - accuracy: 0.8540
Epoch 35/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3453 - accuracy: 0.8542
Epoch 36/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3451 - accuracy: 0.8546
Epoch 37/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3444 - accuracy: 0.8549
Epoch 38/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3446 - accuracy: 0.8563
Epoch 39/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3443 - accuracy: 0.8573
Epoch 40/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3439 - accuracy: 0.8567
Epoch 41/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3433 - accuracy: 0.8579
Epoch 42/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3432 - accuracy: 0.8575
Epoch 43/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3433 - accuracy: 0.8588
Epoch 44/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3427 - accuracy: 0.8579
Epoch 45/100
210/210 [==============================] - 1s 2ms/step - loss: 0.3421 - accuracy: 0.8579
Epoch 46/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3423 - accuracy: 0.8585
Epoch 47/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3422 - accuracy: 0.8596
Epoch 48/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3420 - accuracy: 0.8601
Epoch 49/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3417 - accuracy: 0.8599
Epoch 50/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3416 - accuracy: 0.8609
Epoch 51/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3413 - accuracy: 0.8593
Epoch 52/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3413 - accuracy: 0.8593
Epoch 53/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3409 - accuracy: 0.8581
Epoch 54/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3406 - accuracy: 0.8599
Epoch 55/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3407 - accuracy: 0.8591
Epoch 56/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3403 - accuracy: 0.8593
Epoch 57/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3405 - accuracy: 0.8590
Epoch 58/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3400 - accuracy: 0.8594
Epoch 59/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3399 - accuracy: 0.8591
Epoch 60/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3397 - accuracy: 0.8585
Epoch 61/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3397 - accuracy: 0.8601
Epoch 62/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3398 - accuracy: 0.8600
Epoch 63/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3396 - accuracy: 0.8591
Epoch 64/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3398 - accuracy: 0.8588
Epoch 65/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3393 - accuracy: 0.8597
Epoch 66/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3395 - accuracy: 0.8593
Epoch 67/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3391 - accuracy: 0.8603
Epoch 68/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3389 - accuracy: 0.8600
Epoch 69/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3390 - accuracy: 0.8588
Epoch 70/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3395 - accuracy: 0.8603
Epoch 71/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3389 - accuracy: 0.8603
Epoch 72/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3389 - accuracy: 0.8606
Epoch 73/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3389 - accuracy: 0.8596
Epoch 74/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3387 - accuracy: 0.8597
Epoch 75/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3385 - accuracy: 0.8603
Epoch 76/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3382 - accuracy: 0.8618
Epoch 77/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3391 - accuracy: 0.8597
Epoch 78/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3384 - accuracy: 0.8606
Epoch 79/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3380 - accuracy: 0.8601
Epoch 80/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3383 - accuracy: 0.8618
Epoch 81/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3384 - accuracy: 0.8610
Epoch 82/100
210/210 [==============================] - 1s 2ms/step - loss: 0.3384 - accuracy: 0.8604
Epoch 83/100
210/210 [==============================] - 1s 2ms/step - loss: 0.3381 - accuracy: 0.8607
Epoch 84/100
210/210 [==============================] - 1s 2ms/step - loss: 0.3382 - accuracy: 0.8610
Epoch 85/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3386 - accuracy: 0.8601
Epoch 86/100
210/210 [==============================] - 1s 2ms/step - loss: 0.3380 - accuracy: 0.8609
Epoch 87/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3381 - accuracy: 0.8612
Epoch 88/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3378 - accuracy: 0.8606
Epoch 89/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3380 - accuracy: 0.8604
Epoch 90/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3379 - accuracy: 0.8596
Epoch 91/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3378 - accuracy: 0.8616
Epoch 92/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3380 - accuracy: 0.8618
Epoch 93/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3379 - accuracy: 0.8613
Epoch 94/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3379 - accuracy: 0.8616
Epoch 95/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3374 - accuracy: 0.8607
Epoch 96/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3377 - accuracy: 0.8600
Epoch 97/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3376 - accuracy: 0.8618
Epoch 98/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3375 - accuracy: 0.8619
Epoch 99/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3370 - accuracy: 0.8625
Epoch 100/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3377 - accuracy: 0.8613

## Making the predictions and evaluating the model

In [ ]:
print(ann.predict(sc.transform([[600,1,40,3,60000,2,1,1,50000,1,0,0]]))>0.5)

1/1 [==============================] - 0s 38ms/step
[[False]]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

## Predicting the test set results

In [ ]:
y_preds = ann.predict(X_test)

104/104 [==============================] - 0s 3ms/step

In [ ]:
y_preds = (y_preds > 0.5)

In [ ]:
y_preds

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [ ]:
result = pd.DataFrame(y_test)

In [ ]:
result["prediction"]=y_preds

In [ ]:
result

      Exited  prediction
6252       0       False
4684       0       False
1731       0       False
4742       0       False
4521       0       False
...      ...         ...
1744       0       False
9754       0       False
6094       0       False
8781       0       False
9401       1        True

[3300 rows x 2 columns]

## Making confusion matrix and accuracy

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
confusion_matrix(y_test,y_preds)

array([[2543,  114],
       [ 330,  313]])

In [ ]:
accuracy_score(y_test,y_preds)

0.8654545454545455